task:
  name: Build Web
  skip: "!changesInclude('.cirrus.yml', 'web/**')"
  container:
    image: node:latest
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat web/package-lock.json
    populate_script: make ci-setup-web
  build_script: make build-web

task:
  name: Build Api
  container:
    image: golang:latest
  env:
    GOPROXY: https://proxy.golang.org
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  build_script: make build-api
  test_script: make test-api
  lint_script: make lint
