linters:
  enable-all: true
  disable:
    - gosimple
    - wsl
    - gochecknoinits
    - godox
    - interfacer
run:
  skip-dirs:
    - web
    - representation
issues:
  exclude-rules:
  - path: _test\.go
    linters:
      - gomnd
      - errcheck
