repository:
  type: memory
services:
- name: mock-target
  dns_sd_configs:
  - names:
    - localhost
    refresh_interval: 10s
    type: A
    port: 7778
  scraper:
    endpoint: "/errors"
    refresh_interval: 10s
- name: periskop
  static_configs:
  - targets:
    - localhost:7777
  scraper:
    endpoint: "/errors"
    refresh_interval: 10s
