services:
  - name: mock-target
    service_discovery:
      name: localhost
      refresh_interval: 45s
      type: A
      port: 7778
    scraper:
      endpoint: /errors
      refresh_interval: 30s
